### ISSUE TITLE
Geofencing updates works only when the MainActivity (in the sample) is opened

### ISSUE THREAD

**Issue by shehabic** [mcharmas/Android-ReactiveLocation#29] opened 2015-02-19 01:01 UTC
If the MainActivity from the sample is closed or even Paused, Geofences are never triggered, is there an option to tell it to run in the background ?

**Comment by sytolk** [comment] 2015-02-19 07:57
Yes move Activity code to Application.

**Comment by mcharmas** [comment] 2015-02-19 11:51
It's strange. I've been testing it and it works for me. After setting geofences with proper activity in sample app you can close it. PendingIntent to broadcast receiver should be triggered on geofence transition. Moving code to Application wouldn't make a difference imho. Could you tell more about your setup and try it on different one?

**Comment by shehabic** [comment] 2015-02-19 11:56
I used the sample app, as is, Tried it on Phone and on emulator, I keep faking the position in Genymotion it's quite easy, and on phone when I enable the Mock Locations and using any fake GPS app, I set GeoFence, then I close the app, I move the location outside and inside the fence, nothing happens, then once I open the app again I see the notification (based on the location in that case inside/outside) .. 

I tested this on S4 with kitkat 4.4.2 and in Genymotion on Lolipop 5.0
One more thing, I the same exact behavior in another app using your lib, and from there I decided to compile your sample app to see if it has the same behavior.

**Comment by shehabic** [comment] 2015-02-19 12:01
I have also another question, In my app, I have a background service running all the time and listening to Location Changes.

And an activity that creates Geofences once search results is retrieved from a backend I have, they're not sharing the ReactiveLocation object, each one creates its own instance, and on both the emulator and device, I had this running in the background could it be the reason by any mean?

Could it be that multiple-apps using one of Google Play Services APIs can affect each other by any mean?

**Comment by mcharmas** [comment] 2015-02-19 12:35
I've just checked again and it works. I can send you a video that is testing this behaviour using mock location. What I fixed though is a possiblity to input negative coordinates in geofence setup. I don't think that using multiple location clients should be an issue. Every observable uses it's own location client.

Maybe ratio you are setting is not big enough? I was just testing with 500 meters.

Having a service in background all the time fetching location is not good practice though due to battery consumption but you are probably aware of that.

**Comment by sytolk** [comment] 2015-02-19 15:31
interesting :) how can you receive location update if you have unsubscribe() in Activity onStop() method ?

**Comment by Mohamed-Shehab** [comment] 2015-02-19 15:33
@sytolk Geofence doesn't have subscribe/unsubscribe afaik, you just set BroadcastReceiver to receive updates when Geofence is triggered

**Comment by mcharmas** [comment] 2015-02-19 15:35
@sytolk it's not about location update - its about geofencing. You are registering penging intent in GMS that notifies you when you enter certain area with some probability. Process of your application can be completly gone and still GMS will use pending intent you provided. In case of sample app Android will fire broadcast and fire you app process if it was gone and deliver intent to broadcast receiver.

**Comment by shehabic** [comment] 2015-02-19 15:35
@sytolk Geofence doesn't have subscribe/unsubscribe afaik, you just set BroadcastReceiver to receive updates when Geofence is triggered, for location update I run in a background Service, that triggers the callback every 200m of movement

**Comment by sytolk** [comment] 2015-02-19 15:39
Ok I have never use Geofence but for background location update its not need service. Just move subscription code to Application and not call unsubscribe ;)

**Comment by mcharmas** [comment] 2015-02-19 15:46
@sytolk Its pretty bad practice to do that. App is bound to the location provider even when it's not used by anyone and Android can kill it in anytime. Much better is to let android know that sth is going on and do that in the service or even beter - use alarm manager and wake up some service once in a while to fetch location and unsubscribe afterwards and finish service and not waste resources.

**Comment by shehabic** [comment] 2015-02-19 16:00
@mcharmas anyway in my implementation I'm setting mode to 
```
        locationUpdatesObservable = locationProvider.getUpdatedLocation(
            LocationRequest.create()
                .setPriority(LocationRequest.PRIORITY_LOW_POWER)
                .setFastestInterval(5000)
                .setInterval(30 * (60 * 1000)) // Every 30 mins 
                .setSmallestDisplacement(200f)
        ).subscribe(new Action1<Location>() {
            @Override
            public void call(Location location) {
                     // Call a method to save the location obtained
            } 
        });
```
would this still consume much battery ?

**Comment by mcharmas** [comment] 2015-02-19 16:05
Hmm, everything that works in background uses power especially when uses location services. I guess you should measure it. Here are some resources: https://developer.android.com/about/versions/android-5.0.html#Power. Here I can see that you are fetching location every thirty minutes. In this case I would definitelly consider using alarm manager to wake your service every 30minutres, in service fetch location and do what you've got to do and finish service. In this case you will not waste device resources like memory. Consider also aquiring wakelock for time of service execution, here you have some resources: https://developer.android.com/training/scheduling/wakelock.html.

**Comment by shehabic** [comment] 2015-02-19 16:11
Thanks alot, but isn't it actually 30 mins or 200 m movements for this:
```
.setSmallestDisplacement(200f)
```

**Comment by mcharmas** [comment] 2015-02-19 16:23
Oh, I see. So I guess try measuring it in order to optimize. Closing the issue. If you find a bug with geofencing please reopen it with more details.

**Closed by mcharmas** 2015-02-19 16:23 UTC

**Comment by shehabic** [comment] 2015-02-19 19:57
Hi @mcharmas I'm afraid the issue is happening, I'm uploading a video to Youtube showing it

**Comment by shehabic** [comment] 2015-02-19 23:18
@mcharmas it seems that this:
```.setNumUpdates(5)``` is one of the main reasons, it looks like it's a global thing for Google Play Services API, when I increased it, things worked normally

**Comment by mcharmas** [comment] 2015-02-20 11:27
@shehabic I guess I see where the problem is. Have you tried this using regular device? I had similar problems with genymotion some time ago. I guess these problems are happening because no other application or system is using location services and GMS does this updates by itself rarely. After opening first activity location is being fetched and GMS realizes that some geofences need to be triggered. By the way - GPS location is rarely used by geofencing - i guess it's a mix of locating user by wifi and cellular network most of the time. 

Try this - instead of opening reactive location sample open google maps. The result will be the same because maps are fetching location. 

This is an issue (or intended behavior, due to battery constraints) of geofencing mechanism - not the library.

**Comment by shehabic** [comment] 2015-02-20 13:09
```
This is an issue (or intended behavior, due to battery constraints) of geofencing mechanism - not the library.
```
That would make sense, tonight I'll try to keep a background service listening for location changes (every 30 meters of change) and see what happens, but generally I agree that it's not an issue in your lib. as I can reproduce the same behavior with the official Google-Samples

**Comment by farmazon3000** [comment] 2015-10-21 16:39
I see that you all have forgotten about wakelock - you phone for sure will go asleep after some time and no code will be executed.

**Comment by shehabic** [comment] 2015-10-21 16:50
You're right, but I'm not sure if it affects this, I'll check later when I have time

**Comment by vists** [comment] 2016-02-03 12:14
Hello mcharmas, can I ask you. ReactiveLocation work fine, but when I turn off wifi and mobile network in gps settings and leave "Get location on GPS module" , not work.
