### ISSUE TITLE
Check setNumUpdates and send onComplete

### ISSUE THREAD

**Issue by BraisGabin** [mcharmas/Android-ReactiveLocation#124] opened 2016-07-29 11:37 UTC
I think that `ReactiveLocationProvider.getUpdatedLocation()` must check `LocationRequest.getNumUpdates()` and set a `take()` with that number. To keep a stream open when it's not going to send more events doesn't have sense.

**Comment by sergbek** [comment] 2016-09-04 13:56
it would be very nice

**Comment by mcharmas** [comment] 2017-09-29 09:51
Duplicate of #149. Just fixed.

**Closed by mcharmas** 2017-09-29 09:51 UTC
